# Generated by Django 3.1.7 on 2021-04-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuartel',
            name='cuarteles_limitrofes',
            field=models.ManyToManyField(blank=True, related_name='_cuartel_cuarteles_limitrofes_+', to='fireMap.Cuartel'),
        ),
    ]
