# Generated by Django 3.1.7 on 2021-04-13 00:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('jurisdiccion', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('cuarteles_limitrofes', models.ManyToManyField(related_name='_cuartel_cuarteles_limitrofes_+', to='fireMap.Cuartel')),
            ],
        ),
        migrations.CreateModel(
            name='Incendio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_extincion', models.DateTimeField(blank=True)),
                ('radio', models.FloatField()),
                ('caracteristicas_generales', models.TextField()),
                ('activo', models.BooleanField()),
                ('bomberos_afectados', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('cuarteles_afectados', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fireMap.cuartel')),
            ],
        ),
    ]
