# Generated by Django 3.1.7 on 2021-05-29 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('jurisdiccion', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('fuego_activo', models.BooleanField()),
                ('cuarteles_limitrofes', models.ManyToManyField(blank=True, related_name='_cuartel_cuarteles_limitrofes_+', to='fireMap.Cuartel')),
            ],
        ),
        migrations.CreateModel(
            name='Incendio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_extincion', models.DateTimeField(blank=True, null=True)),
                ('radio', models.FloatField()),
                ('bomberos_afectados', models.IntegerField()),
                ('unid_livianas_afectadas', models.IntegerField()),
                ('unid_pesadas_afectadas', models.IntegerField()),
                ('caracteristica', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
                ('riesgo_interfase', models.BooleanField()),
                ('cuarteles_afectados', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fireMap.cuartel')),
            ],
        ),
    ]
