# Generated by Django 3.1.6 on 2021-07-17 01:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0002_auto_20210602_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incendio',
            name='fecha_hora_extincion',
        ),
        migrations.AlterField(
            model_name='incendio',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
