# Generated by Django 3.1.7 on 2021-04-13 02:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0002_auto_20210413_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuartel',
            name='jurisdiccion',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
