# Generated by Django 3.1.7 on 2021-04-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0004_auto_20210413_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendio',
            name='fecha_hora_extincion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
