# Generated by Django 3.1.6 on 2021-07-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0004_auto_20210729_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendio',
            name='fecha_hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
