# Generated by Django 3.1.7 on 2021-05-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0005_auto_20210413_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incendio',
            name='caracteristicas_generales',
        ),
        migrations.AddField(
            model_name='cuartel',
            name='fuego_activo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incendio',
            name='caracteristica',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incendio',
            name='estado',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incendio',
            name='riesgo_interfase',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incendio',
            name='unid_livianas_afectadas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incendio',
            name='unid_pesadas_afectadas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incendio',
            name='bomberos_afectados',
            field=models.IntegerField(),
        ),
    ]
