# Generated by Django 3.1.6 on 2021-08-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0005_auto_20210729_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuartel',
            name='fuego_activo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
