# Generated by Django 3.1.7 on 2021-05-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0006_auto_20210507_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incendio',
            name='activo',
        ),
    ]
