# Generated by Django 3.1.6 on 2021-08-01 18:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0006_auto_20210801_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuartel',
            name='cuarteles_limitrofes',
            field=models.ManyToManyField(blank=True, null=True, related_name='_cuartel_cuarteles_limitrofes_+', to='fireMap.Cuartel'),
        ),
        migrations.AlterField(
            model_name='cuartel',
            name='jurisdiccion',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
