# Generated by Django 3.1.7 on 2021-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0007_remove_incendio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incendio',
            name='activo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
