# Generated by Django 3.1.6 on 2021-08-01 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0008_auto_20210801_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendio',
            name='cuarteles_afectados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fireMap.cuartel'),
        ),
    ]
