# Generated by Django 3.1.6 on 2021-08-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0009_auto_20210801_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuartel',
            name='cuarteles_limitrofes',
            field=models.ManyToManyField(blank=True, related_name='_cuartel_cuarteles_limitrofes_+', to='fireMap.Cuartel'),
        ),
    ]
