# Generated by Django 3.1.6 on 2021-08-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0010_auto_20210804_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuartel',
            name='fuego_activo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.RemoveField(
            model_name='incendio',
            name='cuarteles_afectados',
        ),
        migrations.AddField(
            model_name='incendio',
            name='cuarteles_afectados',
            field=models.ManyToManyField(blank=True, to='fireMap.Cuartel'),
        ),
    ]
