# Generated by Django 3.1.6 on 2021-08-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireMap', '0012_auto_20210811_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incendio',
            name='cuarteles_afectados',
            field=models.ManyToManyField(blank=True, to='fireMap.Cuartel'),
        ),
    ]
